name: Generate Images

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ORG: fabric8-analytics
  REPO: crda-images

jobs:
  Build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        versions:
          - ecosystem: python
            package:  python3
            tag: python3
            path: Dockerfiles/Dockerfile.python
          - ecosystem: python
            package:  python36
            tag: python36
            path: Dockerfiles/Dockerfile.python
          - ecosystem: python
            package:  python38
            tag: python38
            path: Dockerfiles/Dockerfile.python
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push ${{ matrix.versions.ecosystem }}-${{ matrix.versions.package }}
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./${{ matrix.versions.path }}
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.ORG }}/crda:${{ matrix.versions.tag }}
        build-args: ECOSYSTEM_VERSION=${{ matrix.versions.package}}